/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AccessTokenPermissionResponse } from './accessTokenPermissionResponse';


export interface AccessTokenResponse { 
    id: string;
    accessToken: string;
    organizationId: string;
    permissions: Array<AccessTokenPermissionResponse>;
}

