/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SmartContractType = 'Erc20' | 'Erc721' | 'Custom';

export const SmartContractType = {
    Erc20: 'Erc20' as SmartContractType,
    Erc721: 'Erc721' as SmartContractType,
    Custom: 'Custom' as SmartContractType
};

