/**
 * Kriptonio.Rpc.Rest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApiErrorCode = 11000 | 11001 | 11002 | 11003 | 11004 | 11005 | 11006 | 11007 | 11008 | 11009 | 11010 | 11011 | 11012 | 11013 | 11014 | 11015 | 11016 | 11017 | 11018;

export const ApiErrorCode = {
    NUMBER_11000: 11000 as ApiErrorCode,
    NUMBER_11001: 11001 as ApiErrorCode,
    NUMBER_11002: 11002 as ApiErrorCode,
    NUMBER_11003: 11003 as ApiErrorCode,
    NUMBER_11004: 11004 as ApiErrorCode,
    NUMBER_11005: 11005 as ApiErrorCode,
    NUMBER_11006: 11006 as ApiErrorCode,
    NUMBER_11007: 11007 as ApiErrorCode,
    NUMBER_11008: 11008 as ApiErrorCode,
    NUMBER_11009: 11009 as ApiErrorCode,
    NUMBER_11010: 11010 as ApiErrorCode,
    NUMBER_11011: 11011 as ApiErrorCode,
    NUMBER_11012: 11012 as ApiErrorCode,
    NUMBER_11013: 11013 as ApiErrorCode,
    NUMBER_11014: 11014 as ApiErrorCode,
    NUMBER_11015: 11015 as ApiErrorCode,
    NUMBER_11016: 11016 as ApiErrorCode,
    NUMBER_11017: 11017 as ApiErrorCode,
    NUMBER_11018: 11018 as ApiErrorCode
};

