/**
 * Kriptonio.Rpc.Rest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ExternalServiceError } from './externalServiceError';
import type { ApiErrorCode } from './apiErrorCode';


export interface ApiErrorResponse { 
    code: ApiErrorCode;
    message?: string | null;
    cause?: ExternalServiceError;
}
export namespace ApiErrorResponse {
}


