/**
 * Kriptonio.Rpc.Rest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { EndpointCallStatus } from './endpointCallStatus';


export interface BlockchainEndpointCallResponse { 
    requestBody?: string | null;
    method?: string | null;
    errorMessage?: string | null;
    errorCode?: number | null;
    status: EndpointCallStatus;
    httpCode: number;
    createdAt: string;
}
export namespace BlockchainEndpointCallResponse {
}


