/**
 * Kriptonio.Rpc.Rest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { BlockchainEndpointCallResponse } from './blockchainEndpointCallResponse';


export interface BlockchainEndpointCallResponsePaged { 
    items: Array<BlockchainEndpointCallResponse>;
    count: number;
    pageSize: number;
}

