/**
 * Kriptonio Paymaster API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymasterResponse { 
    id: string;
    chainId: number;
    type: PaymasterResponse.TypeEnum;
    createdAt: string;
}
export namespace PaymasterResponse {
    export type TypeEnum = 'verifying_fiat';
    export const TypeEnum = {
        VerifyingFiat: 'verifying_fiat' as TypeEnum
    };
}


