/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { OrganizationSubscriptionLimitResponse } from './organizationSubscriptionLimitResponse';
import type { SubscriptionStatus } from './subscriptionStatus';


export interface OrganizationSubscriptionResponse { 
    subscriptionPlanId: string;
    planType: string;
    isFree: boolean;
    status: SubscriptionStatus;
    stripeMeteredPaymasterSubscriptionItemId?: string | null;
    subscriptionLimit: OrganizationSubscriptionLimitResponse;
}
export namespace OrganizationSubscriptionResponse {
}


