/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { OrganizationSubscriptionResponse } from './organizationSubscriptionResponse';
import type { OrganizationMemberResponse } from './organizationMemberResponse';
import type { OrganizationInvitationResponse } from './organizationInvitationResponse';


export interface OrganizationDetailResponse { 
    id: string;
    name: string;
    slug: string;
    isPersonal: boolean;
    subscription: OrganizationSubscriptionResponse;
    members: Array<OrganizationMemberResponse>;
    invitations: Array<OrganizationInvitationResponse>;
}

