/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SubscriptionPlanType } from './subscriptionPlanType';


export interface SubscriptionPlanResponse { 
    id: string;
    planType: SubscriptionPlanType;
    isFree: boolean;
    mostPopular: boolean;
    bestValue: boolean;
}
export namespace SubscriptionPlanResponse {
}


