/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { InputType } from './inputType';


export interface TemplateInputPropertyResponse { 
    key: string;
    title: string;
    type: InputType;
    isRequired: boolean;
    defaultValue: any | null;
    help?: string | null;
}
export namespace TemplateInputPropertyResponse {
}


