/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AuthMethod } from './authMethod';


export interface UserResponse { 
    id: string;
    firstName: string;
    lastName: string;
    mobileDecryptionKey: string;
    email?: string | null;
    twoFactorEnabled: boolean;
    authMethod: AuthMethod;
}
export namespace UserResponse {
}


